INSERT INTO customers (fullName, email, phone)
SELECT
    CONCAT(
        UPPER(SUBSTRING(MD5(RAND()), 1, 1)), LOWER(SUBSTRING(MD5(RAND()), 2, 6)), ' ',
        UPPER(SUBSTRING(MD5(RAND()), 1, 1)), LOWER(SUBSTRING(MD5(RAND()), 2, 7))
    ) AS fullName,
    CONCAT(LOWER(SUBSTRING(MD5(RAND()), 1, 10)), '@example.com') AS email,
    CONCAT('+1-', LPAD(FLOOR(RAND() * 10000000000), 10, '0')) AS phone
FROM (
    SELECT @row := @row + 1
    FROM (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
         (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
         (SELECT @row := 0) r
    LIMIT 100
) AS seqs;

INSERT INTO items (itemName, category, price)
SELECT
    CONCAT('Item ', @row := @row + 1) AS itemName,
    ELT(FLOOR(1 + (RAND() * 5)), 'Electronics', 'Clothing', 'Books', 'Home', 'Toys') AS category,
    ROUND(1 + (RAND() * 100), 2) AS price
FROM (
    SELECT @row := 0
) init, 
(
    SELECT 1 FROM 
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) a,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) b
    LIMIT 50
) filler;

INSERT INTO orders (customerID, itemID, quantity, orderDate)
SELECT
    (SELECT customerID FROM customers ORDER BY RAND() LIMIT 1),
    (SELECT itemID FROM items ORDER BY RAND() LIMIT 1),
    FLOOR(1 + (RAND() * 5)),
    DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND() * 365) DAY)
FROM (
    SELECT 1 FROM 
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    LIMIT 200
) filler;
